services:
  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - /etc/docker/registry/data:/var/lib/registry


  nginx:
    restart: always
    image: nginx:1.27.2
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd
